; 8086 Assembly Generated by Compiler
.model small
.stack 100h
.data
.code
start_program:
    MOV AX, @data
    MOV DS, AX
    CALL main
    MOV AX, 4C00h
    INT 21h


calculate:
    PUSH BP
    MOV BP, SP
    SUB SP, 4 ; Reserve locals
    MOV AX, [BP+4] ; Load Param x
    MOV BX, [BP+6] ; Load Param y
    ADD AX, BX
    MOV [BP-2], AX
    MOV SP, BP
    POP BP
    RET

main:
    PUSH BP
    MOV BP, SP
    SUB SP, 6 ; Reserve locals
    MOV AX, 15
    MOV [BP-2], AX
    MOV SP, BP
    POP BP
    RET

_print_int:
    PUSH BP
    MOV BP, SP
    MOV AX, [BP+4]
    ADD AX, '0' ; Hack: only works for single digit 0-9
    MOV DX, AX
    MOV AH, 02h
    INT 21h
    POP BP
    RET
