#include "code_gen.h"
#include <string.h>

/*
 * currentScope is shared with the semantic analyzer.
 * It allows code generation to retrieve symbol offsets
 * (parameters / locals) using the symbol table.
 */
extern Scope *currentScope;

// =========================================================
// REGISTER DESCRIPTOR
// =========================================================
// We track which variable is currently in which register
// to avoid redundant loads from memory.
//
// This is a *very simple* register allocation strategy:
// - No spilling to memory (assumed not needed)
// - One variable per register
// - Register content invalidated on arithmetic operations
typedef struct {
    int is_free;       // 1 if register is free, 0 if occupied
    char *content;    // Variable name currently stored in this register
} Register;

// ---------------------------------------------------------
// 8086 has four general-purpose registers usable here
// AX, BX, CX, DX
// ---------------------------------------------------------
Register regs[4] = {
    {1, NULL}, {1, NULL}, {1, NULL}, {1, NULL}
};

// Assembly register names corresponding to regs[]
char* reg_names[] = { "AX", "BX", "CX", "DX" };

// =========================================================
// REGISTER MANAGEMENT HELPERS
// =========================================================

/*
 * get_free_reg:
 *   Finds a free register and marks it as occupied.
 *   This is a very naive allocator:
 *     - No register spilling is implemented
 *     - Compilation fails if all registers are exhausted
 */
int get_free_reg(FILE *fp) {
    for(int i=0; i<4; i++) {
        if(regs[i].is_free) {
            regs[i].is_free = 0;
            return i;
        }
    }

    // Spill logic (Simplest: Push AX, assume it's freed, user handles restore)
    // For this project, we assume expressions aren't complex enough to run out.
    fprintf(stderr, "CodeGen Error: Register exhaustion.\n");
    return 0; // Fallback to AX
}

/*
 * free_reg:
 *   Marks a register as free.
 *   Also clears its descriptor content since the value is no longer valid.
 */
void free_reg(int r) {
    if(r>=0 && r<4) {
        regs[r].is_free = 1;
        if(regs[r].content) {
            free(regs[r].content);
            regs[r].content = NULL;
        }
    }
}

// =========================================================
// SMART REGISTER FETCH FOR VARIABLES
// =========================================================

/*
 * get_reg_for_var:
 *   Returns a register holding the given variable.
 *
 *   Optimization:
 *     - If the variable is already loaded in some register,
 *       reuse that register.
 *     - Otherwise, load from memory (stack frame) into a free register.
 *
 *   offset:
 *     - >= 0 → parameter (BP+offset)
 *     - < 0  → local variable (BP-offset)
 */
int get_reg_for_var(char *varName, int offset, FILE *fp) {

    // 1. Check Register Descriptor (reuse if already loaded)
    for(int i=0; i<4; i++) {
        if(!regs[i].is_free &&
           regs[i].content &&
           strcmp(regs[i].content, varName) == 0) {
            return i; // Variable already in register
        }
    }
    
    // 2. Load variable from stack frame
    int r = get_free_reg(fp);

    if (offset >= 0)
        fprintf(fp, "    MOV %s, [BP+%d] ; Load Param %s\n",
                reg_names[r], offset, varName);
    else
        fprintf(fp, "    MOV %s, [BP%d] ; Load Local %s\n",
                reg_names[r], offset, varName);
        
    // 3. Update register descriptor
    regs[r].content = strdup(varName);

    return r;
}

// =========================================================
// LABEL GENERATION
// =========================================================

/*
 * lbl_counter:
 *   Global monotonically increasing label ID.
 *   Ensures uniqueness for IF, loops, etc.
 */
int lbl_counter = 0;

/*
 * new_label:
 *   Returns a new unique label number.
 */
int new_label() { return lbl_counter++; }

// =========================================================
// CODE GENERATION INITIALIZATION
// =========================================================

/*
 * code_gen_init:
 *   Emits program-level assembly boilerplate.
 *   Sets up:
 *     - Memory model
 *     - Stack
 *     - Data segment
 *     - Program entry point
 */
void code_gen_init(FILE *fp) {
    fprintf(fp, "; 8086 Assembly Generated by Compiler\n");
    
    // 1. Define memory model and stack size
    fprintf(fp, ".model small\n"); 
    fprintf(fp, ".stack 100h\n");

    // 2. Data Segment (no ORG needed for .EXE)
    fprintf(fp, ".data\n");
    
    // 3. Code Segment
    fprintf(fp, ".code\n");
    
    // 4. Program entry label
    fprintf(fp, "start_program:\n"); 

    // 5. Initialize DS register (MANDATORY in 8086)
    fprintf(fp, "    MOV AX, @data\n");
    fprintf(fp, "    MOV DS, AX\n");

    // 6. Call compiled main() function
    fprintf(fp, "    CALL main\n");

    // 7. Exit to DOS
    fprintf(fp, "    MOV AX, 4C00h\n");
    fprintf(fp, "    INT 21h\n\n");
    
}

// =========================================================
// MAIN CODE GENERATOR (AST → ASM)
// =========================================================

/*
 * code_gen:
 *   Recursive code generator.
 *   Returns:
 *     - Register number containing result (for expressions)
 *     - -1 for statements
 */
int code_gen(ASTNode *node, FILE *fp) {
    if (!node) return -1;
    
    int r1, r2, lbl1, lbl2;

    switch(node->kind) {
        
        // -------------------------------------------------
        // INTEGER LITERAL
        // -------------------------------------------------
        case NODE_LITERAL_INT:
            r1 = get_free_reg(fp);
            fprintf(fp, "    MOV %s, %d\n",
                    reg_names[r1], node->int_val);
            return r1;

        // -------------------------------------------------
        // VARIABLE ACCESS
        // -------------------------------------------------
        case NODE_VAR_ACCESS:
            {
                // Look up symbol for stack offset
                Symbol *s = sym_lookup(node->name);
                if (!s) {
                    fprintf(fp, "; Error: Var %s not found\n", node->name);
                    return get_free_reg(fp);
                }
                // Use smart register loading
                return get_reg_for_var(s->name, s->offset, fp);
            }

        // -------------------------------------------------
        // ASSIGNMENT
        // -------------------------------------------------
        case NODE_ASSIGN:
            // 1. Generate RHS expression
            r1 = code_gen(node->right, fp);

            // 2. Store into LHS variable memory
            if(node->left->kind == NODE_VAR_ACCESS) {
                Symbol *s = sym_lookup(node->left->name);
                if(s) {
                    if(s->offset >= 0)
                        fprintf(fp, "    MOV [BP+%d], %s\n",
                                s->offset, reg_names[r1]);
                    else
                        fprintf(fp, "    MOV [BP%d], %s\n",
                                s->offset, reg_names[r1]);
                    
                    // Update descriptor: register now represents this variable
                    if(regs[r1].content) free(regs[r1].content);
                    regs[r1].content = strdup(s->name);
                }
            }
            free_reg(r1);
            return -1;

        // -------------------------------------------------
        // BINARY EXPRESSION (8086-COMPLIANT)
        // -------------------------------------------------
       
        case NODE_EXPR_BINOP:
            r1 = code_gen(node->left, fp);
            r2 = code_gen(node->right, fp);

            // Arithmetic invalidates previous variable meaning
            if (regs[r1].content) {
                free(regs[r1].content);
                regs[r1].content = NULL;
            }

            // ---------------- ADD ----------------
            if (strcmp(node->op, "+") == 0) {
                fprintf(fp, "    ADD %s, %s\n",
                        reg_names[r1], reg_names[r2]);
            }

            // ---------------- SUB ----------------
            else if (strcmp(node->op, "-") == 0) {
                fprintf(fp, "    SUB %s, %s\n",
                        reg_names[r1], reg_names[r2]);
            }

            // ---------------- MUL ----------------
            else if (strcmp(node->op, "*") == 0) {
                /*
                * AX ← left
                * IMUL right
                * AX ← result
                */
                if (r1 != 0)
                    fprintf(fp, "    MOV AX, %s\n", reg_names[r1]);

                fprintf(fp, "    IMUL %s\n", reg_names[r2]);

                if (r1 != 0)
                    fprintf(fp, "    MOV %s, AX\n", reg_names[r1]);
            }

            // ---------------- DIV ----------------
            else if (strcmp(node->op, "/") == 0) {
                /*
                * 8086 signed division
                *
                * DX:AX ← dividend
                * IDIV divisor
                * AX ← quotient
                * DX ← remainder
                */

                if (r1 != 0)
                    fprintf(fp, "    MOV AX, %s\n", reg_names[r1]);

                fprintf(fp, "    CWD\n");              // Sign-extend AX → DX
                fprintf(fp, "    IDIV %s\n", reg_names[r2]);

                if (r1 != 0)
                    fprintf(fp, "    MOV %s, AX\n", reg_names[r1]);
            }

            // ---------------- GREATER THAN ----------------
            else if (strcmp(node->op, ">") == 0) {
                int lbl_true = new_label();
                int lbl_end  = new_label();

                fprintf(fp, "    CMP %s, %s\n",
                        reg_names[r1], reg_names[r2]);
                fprintf(fp, "    JG L_true_%d\n", lbl_true);

                fprintf(fp, "    MOV %s, 0\n", reg_names[r1]);
                fprintf(fp, "    JMP L_end_%d\n", lbl_end);

                fprintf(fp, "L_true_%d:\n", lbl_true);
                fprintf(fp, "    MOV %s, 1\n", reg_names[r1]);

                fprintf(fp, "L_end_%d:\n", lbl_end);
            }

            free_reg(r2);
            return r1;


        // -------------------------------------------------
        // FUNCTION DEFINITION
        // -------------------------------------------------
        case NODE_FUNC_DEF:
            // Bind scope for symbol lookup inside function
            if(node->scope) currentScope = node->scope; 

            fprintf(fp, "\n%s:\n", node->name);
            fprintf(fp, "    PUSH BP\n");
            fprintf(fp, "    MOV BP, SP\n");
            
            // Allocate stack space for locals
            if (node->scope && node->scope->totalStackSize > 0) {
                fprintf(fp,
                        "    SUB SP, %d ; Reserve locals\n",
                        node->scope->totalStackSize);
            }
            
            // Generate function body
            code_gen(node->right, fp);
            
            // Default epilogue
            fprintf(fp, "    MOV SP, BP\n");
            fprintf(fp, "    POP BP\n");
            fprintf(fp, "    RET\n");
            
            // Restore enclosing scope
            if(node->scope) currentScope = node->scope->parent; 
            return -1;

        // -------------------------------------------------
        // RETURN STATEMENT
        // -------------------------------------------------
        case NODE_RETURN:
            if(node->left) {
                r1 = code_gen(node->left, fp);
                if (r1 != 0)
                    fprintf(fp, "    MOV AX, %s\n",
                            reg_names[r1]); // Return value in AX
                free_reg(r1);
            }
            fprintf(fp, "    MOV SP, BP\n");
            fprintf(fp, "    POP BP\n");
            fprintf(fp, "    RET\n");
            return -1;
            
        // -------------------------------------------------
        // FUNCTION CALL
        // -------------------------------------------------
        case NODE_FUNC_CALL:
            {
                int bytes = 0;

                // Arguments passed right-to-left (stack)
                ASTNode *arg = node->left ? node->left->left : NULL;
                while(arg) {
                    r1 = code_gen(arg->left ? arg->left : arg, fp);
                    fprintf(fp, "    PUSH %s\n", reg_names[r1]);
                    free_reg(r1);
                    bytes += 2;
                    arg = arg->next;
                }

                fprintf(fp, "    CALL %s\n", node->name);
                fprintf(fp, "    ADD SP, %d\n", bytes); // Caller cleans stack

                // Capture return value
                r1 = get_free_reg(fp);
                fprintf(fp, "    MOV %s, AX\n", reg_names[r1]);
                return r1;
            }

        // -------------------------------------------------
        // IF STATEMENT
        // -------------------------------------------------
        case NODE_IF:
            lbl1 = new_label();
            lbl2 = new_label();

            r1 = code_gen(node->left, fp);
            fprintf(fp,
                    "    CMP %s, 0\n    JE L_else_%d\n",
                    reg_names[r1], lbl1);
            free_reg(r1);

            code_gen(node->right, fp);
            fprintf(fp, "    JMP L_end_%d\n", lbl2);

            fprintf(fp, "L_else_%d:\n", lbl1);
            if(node->extra) code_gen(node->extra, fp);

            fprintf(fp, "L_end_%d:\n", lbl2);
            return -1;

        // -------------------------------------------------
        // BLOCK (SEQUENCE OF STATEMENTS)
        // -------------------------------------------------
        case NODE_BLOCK:
            {
                ASTNode *child = node->left;
                while(child) {
                    code_gen(child, fp);
                    child = child->next;
                }
            }
            return -1;

        // -------------------------------------------------
        // WRITE STATEMENT
        // -------------------------------------------------
        case NODE_WRITE:
            r1 = code_gen(node->left, fp);
            fprintf(fp,
                    "    PUSH %s\n"
                    "    CALL _print_int\n"
                    "    ADD SP, 2\n",
                    reg_names[r1]);
            free_reg(r1);
            return -1;

        // -------------------------------------------------
        // FALLBACK
        // -------------------------------------------------
        default:
            if(node->left)  code_gen(node->left, fp);
            if(node->right) code_gen(node->right, fp);
            if(node->next)  code_gen(node->next, fp);
            return -1;
    }
}

// =========================================================
// RUNTIME SUPPORT ROUTINES
// =========================================================

/*
 * code_gen_finalize:
 *   Emits helper routines required by generated code.
 *   Currently provides a minimal integer printer.
 */
void code_gen_finalize(FILE *fp) {

    // Minimal Integer Printer
    fprintf(fp, "\n_print_int:\n");
    fprintf(fp, "    PUSH BP\n    MOV BP, SP\n");
    fprintf(fp, "    MOV AX, [BP+4]\n");
    fprintf(fp, "    ADD AX, '0' ; Hack: only works for single digit 0-9\n");
    fprintf(fp, "    MOV DX, AX\n    MOV AH, 02h\n    INT 21h\n");
    fprintf(fp, "    POP BP\n    RET\n");
    fprintf(fp, "    \n END\n");
}
