#include "code_gen.h"
#include <string.h>

extern Scope *currentScope;

// --- REGISTER DESCRIPTOR ---
// We track which variable is currently in which register to avoid redundant loads.
typedef struct {
    int is_free;
    char *content; // Name of the variable currently held
} Register;

// 8086: AX, BX, CX, DX
Register regs[4] = {
    {1, NULL}, {1, NULL}, {1, NULL}, {1, NULL}
};
char* reg_names[] = { "AX", "BX", "CX", "DX" };

// Helpers
int get_free_reg(FILE *fp) {
    for(int i=0; i<4; i++) {
        if(regs[i].is_free) {
            regs[i].is_free = 0;
            return i;
        }
    }
    // Spill logic (Simplest: Push AX, assume it's freed, user handles restore)
    // For this project, we assume expressions aren't complex enough to run out.
    fprintf(stderr, "CodeGen Error: Register exhaustion.\n");
    return 0; // Fallback
}

void free_reg(int r) {
    if(r>=0 && r<4) {
        regs[r].is_free = 1;
        if(regs[r].content) {
            free(regs[r].content);
            regs[r].content = NULL;
        }
    }
}

// "Smart" Get: Check if var is already loaded
int get_reg_for_var(char *varName, int offset, FILE *fp) {
    // 1. Check Descriptor
    for(int i=0; i<4; i++) {
        if(!regs[i].is_free && regs[i].content && strcmp(regs[i].content, varName) == 0) {
            return i; // Already loaded!
        }
    }
    
    // 2. Load
    int r = get_free_reg(fp);
    if (offset >= 0)
        fprintf(fp, "    MOV %s, [BP+%d] ; Load Param %s\n", reg_names[r], offset, varName);
    else
        fprintf(fp, "    MOV %s, [BP%d] ; Load Local %s\n", reg_names[r], offset, varName);
        
    // 3. Update Descriptor
    regs[r].content = strdup(varName);
    return r;
}

// Label Gen
int lbl_counter = 0;
int new_label() { return lbl_counter++; }

// --- MAIN GENERATOR ---

void code_gen_init(FILE *fp) {
    fprintf(fp, "; 8086 Assembly Generated by Compiler\n");
    fprintf(fp, "BITS 16\nORG 100h\n");
    fprintf(fp, "SECTION .text\n");
    fprintf(fp, "global _start\n_start:\n");
    fprintf(fp, "    CALL main\n");
    fprintf(fp, "    MOV AX, 4C00h\n    INT 21h\n\n");
}

int code_gen(ASTNode *node, FILE *fp) {
    if (!node) return -1;
    
    int r1, r2, lbl1, lbl2;

    switch(node->kind) {
        
        case NODE_LITERAL_INT:
            r1 = get_free_reg(fp);
            fprintf(fp, "    MOV %s, %d\n", reg_names[r1], node->int_val);
            return r1;

        case NODE_VAR_ACCESS:
            {
                // We need to look up the symbol to get the offset
                Symbol *s = sym_lookup(node->name);
                if (!s) {
                    fprintf(fp, "; Error: Var %s not found\n", node->name);
                    return get_free_reg(fp);
                }
                // Use Smart Load
                return get_reg_for_var(s->name, s->offset, fp);
            }

        case NODE_ASSIGN:
            // 1. RHS
            r1 = code_gen(node->right, fp);
            // 2. LHS Address
            if(node->left->kind == NODE_VAR_ACCESS) {
                Symbol *s = sym_lookup(node->left->name);
                if(s) {
                    if(s->offset >= 0)
                        fprintf(fp, "    MOV [BP+%d], %s\n", s->offset, reg_names[r1]);
                    else
                        fprintf(fp, "    MOV [BP%d], %s\n", s->offset, reg_names[r1]);
                    
                    // Update descriptor: r1 now contains 's->name'
                    if(regs[r1].content) free(regs[r1].content);
                    regs[r1].content = strdup(s->name);
                }
            }
            free_reg(r1);
            return -1;

        case NODE_EXPR_BINOP:
            r1 = code_gen(node->left, fp);
            r2 = code_gen(node->right, fp);
            
            // Operation invalidates the content of the destination register
            if(regs[r1].content) { free(regs[r1].content); regs[r1].content = NULL; }

            if(strcmp(node->op, "+")==0) fprintf(fp, "    ADD %s, %s\n", reg_names[r1], reg_names[r2]);
            else if(strcmp(node->op, "-")==0) fprintf(fp, "    SUB %s, %s\n", reg_names[r1], reg_names[r2]);
            else if(strcmp(node->op, "*")==0) fprintf(fp, "    IMUL %s, %s\n", reg_names[r1], reg_names[r2]);
            else if(strcmp(node->op, ">")==0) {
                 fprintf(fp, "    CMP %s, %s\n", reg_names[r1], reg_names[r2]);
                 fprintf(fp, "    SETG AL\n    CBW\n"); // Result in AX
                 if(r1 != 0) fprintf(fp, "    MOV %s, AX\n", reg_names[r1]); 
            }
            free_reg(r2);
            return r1;

        case NODE_FUNC_DEF:
            // Re-bind global scope pointer for symbol lookups inside this function
            // (In a full implementation, we'd manage a stack of scopes)
            if(node->scope) currentScope = node->scope; 

            fprintf(fp, "\n%s:\n", node->name);
            fprintf(fp, "    PUSH BP\n");
            fprintf(fp, "    MOV BP, SP\n");
            
            // BEST PRACTICE: Use the pre-calculated stack size!
            if (node->scope && node->scope->totalStackSize > 0) {
                fprintf(fp, "    SUB SP, %d ; Reserve locals\n", node->scope->totalStackSize);
            }
            
            code_gen(node->right, fp); // Body
            
            // Default return in case user didn't write one
            fprintf(fp, "    MOV SP, BP\n");
            fprintf(fp, "    POP BP\n");
            fprintf(fp, "    RET\n");
            
            // Restore global scope (hack for this simple architecture)
            if(node->scope) currentScope = node->scope->parent; 
            return -1;

        case NODE_RETURN:
            if(node->left) {
                r1 = code_gen(node->left, fp);
                if (r1 != 0) fprintf(fp, "    MOV AX, %s\n", reg_names[r1]); // Retval in AX
                free_reg(r1);
            }
            fprintf(fp, "    MOV SP, BP\n");
            fprintf(fp, "    POP BP\n");
            fprintf(fp, "    RET\n");
            return -1;
            
        case NODE_FUNC_CALL:
            // Push args (iterate list)
            {
                int bytes = 0;
                ASTNode *arg = node->left ? node->left->left : NULL; // node->left is NODE_LIST
                while(arg) {
                    r1 = code_gen(arg->left ? arg->left : arg, fp); // Handle list wrapper
                    fprintf(fp, "    PUSH %s\n", reg_names[r1]);
                    free_reg(r1);
                    bytes += 2;
                    arg = arg->next;
                }
                fprintf(fp, "    CALL %s\n", node->name);
                fprintf(fp, "    ADD SP, %d\n", bytes);
                r1 = get_free_reg(fp);
                fprintf(fp, "    MOV %s, AX\n", reg_names[r1]);
                return r1;
            }

        case NODE_IF:
            lbl1 = new_label(); lbl2 = new_label();
            r1 = code_gen(node->left, fp);
            fprintf(fp, "    CMP %s, 0\n    JE L_else_%d\n", reg_names[r1], lbl1);
            free_reg(r1);
            code_gen(node->right, fp);
            fprintf(fp, "    JMP L_end_%d\n", lbl2);
            fprintf(fp, "L_else_%d:\n", lbl1);
            if(node->extra) code_gen(node->extra, fp);
            fprintf(fp, "L_end_%d:\n", lbl2);
            return -1;

        case NODE_BLOCK:
            {
                ASTNode *child = node->left;
                while(child) {
                    code_gen(child, fp);
                    child = child->next;
                }
            }
            return -1;

        case NODE_WRITE:
            r1 = code_gen(node->left, fp);
            fprintf(fp, "    PUSH %s\n    CALL _print_int\n    ADD SP, 2\n", reg_names[r1]);
            free_reg(r1);
            return -1;

        default:
            if(node->left) code_gen(node->left, fp);
            if(node->right) code_gen(node->right, fp);
            if(node->next) code_gen(node->next, fp);
            return -1;
    }
}

void code_gen_finalize(FILE *fp) {
    // Minimal Integer Printer
    fprintf(fp, "\n_print_int:\n");
    fprintf(fp, "    PUSH BP\n    MOV BP, SP\n");
    fprintf(fp, "    MOV AX, [BP+4]\n");
    fprintf(fp, "    ADD AX, '0' ; Hack: only works for single digit 0-9\n");
    fprintf(fp, "    MOV DX, AX\n    MOV AH, 02h\n    INT 21h\n");
    fprintf(fp, "    POP BP\n    RET\n");
}