; 8086 Assembly Generated by Compiler
BITS 16
ORG 100h
SECTION .text
global _start
_start:
    CALL main
    MOV AX, 4C00h
    INT 21h


main:
    PUSH BP
    MOV BP, SP
    SUB SP, 6 ; Reserve locals
    MOV AX, 10
    MOV [BP-2], AX
    MOV SP, BP
    POP BP
    RET

main:
    PUSH BP
    MOV BP, SP
    SUB SP, 6 ; Reserve locals
    MOV AX, 10
    MOV [BP-2], AX
    MOV SP, BP
    POP BP
    RET

_print_int:
    PUSH BP
    MOV BP, SP
    MOV AX, [BP+4]
    ADD AX, '0' ; Hack: only works for single digit 0-9
    MOV DX, AX
    MOV AH, 02h
    INT 21h
    POP BP
    RET
