CC = gcc
LEX = flex
YACC = bison

LEX_FILE = lexer.l
YACC_FILE = parser.y

LEX_OUT = lex.yy.c
YACC_OUT = parser.tab.c
YACC_HDR = parser.tab.h

TARGET = parser

CFLAGS = -Wall

all: $(TARGET)

$(TARGET): $(LEX_OUT) $(YACC_OUT)
	$(CC) $(CFLAGS) $(LEX_OUT) $(YACC_OUT) -o $(TARGET)

$(LEX_OUT): $(LEX_FILE)
	$(LEX) $(LEX_FILE)

$(YACC_OUT): $(YACC_FILE)
	$(YACC) -d $(YACC_FILE)

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(TARGET) $(LEX_OUT) $(YACC_OUT) $(YACC_HDR) parser.output
